name: Telegram Details Fetcher

on:
  workflow_dispatch:

jobs:
  forward_messages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: 
        pip install -r requirements.txt
    
    - name: Decode Telegram Session
      env:
        TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
      run: echo "${TELEGRAM_SESSION}" | base64 -d > userbot_session.session
    
    - name: Run Telegram Details Fetcher
      env:
        TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
        TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
      run: python src/fetch_my_details.py
