name: Telegram Bot Script

on:
  schedule:
    - cron: '*/6 * * * *'  # Runs every 6 hours
  workflow_dispatch:

concurrency:
  group: 'telegram-bot-script'
  cancel-in-progress: false

jobs:
  forward_messages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: 
        pip install -r requirements.txt
    
    - name: Decode Telegram Session
      env:
        TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
      run: echo "${TELEGRAM_SESSION}" | base64 -d > userbot_session.session
    
    - name: Run Telegram Bot Script
      env:
        TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
        TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
        SOURCE: ${{ secrets.SOURCE }}
        TARGET: ${{ secrets.TARGET }}
        TWITTER_CHANNEL: ${{ secrets.TWITTER_CHANNEL }}
        ERROR_NOTIFY: ${{ secrets.ERROR_NOTIFY }}
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      run: python src/main.py
