name: Telegram Message Forwarder

on:
  schedule:
    - cron: '*/330 * * * *'  # Every 5 hours and 30 minutes to avoid hitting the 6-hour limit
  workflow_dispatch:

concurrency:
  group: 'telegram-message-forwarder'
  cancel-in-progress: true

jobs:
  forward_messages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install telethon

    - name: Run Telegram Message Forwarder
      env:
        TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
        TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
        SOURCE: ${{ secrets.SOURCE }}
        TARGET: ${{ secrets.TARGET }}
        ERROR_NOTIFY: ${{ secrets.ERROR_NOTIFY }}
        TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
      run: |
        echo "${TELEGRAM_SESSION}" | base64 -d > userbot_session.session
        python src/main.py
